// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { ldb } from "@/lib/local-db";
import { registerRawClientGetter } from "@/lib/sync-service";

/**
 * Global fetch with a hard 3-second timeout injected into Supabase.
 * Every request across the entire app now fails fast when the backend
 * is unreachable — no per-call wrappers needed, retries are also bounded.
 */
function timeoutFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 10_000);
  return fetch(input, { ...init, signal: controller.signal })
    .catch((err: Error) => {
      clearTimeout(timer);
      if (err.name === "AbortError") {
        throw new Error("Server is offline. Changes cannot be saved right now.");
      }
      throw err;
    })
    .finally(() => clearTimeout(timer));
}

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || "https://icjeiuuqvysjakhubcgaw.supabase.co";
  const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_KEY) {
    console.error("Missing Supabase API Key in .env");
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_KEY || "", {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: false, // Don't keep retrying auth when offline
    },
    global: {
      fetch: timeoutFetch, // ← The root fix: every request times out in 3s
    },
    realtime: {
      reconnectAfterMs: () => 60_000, // Don't spam reconnect attempts
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

/**
 * Module-level cached flag: true when the Supabase client has an active
 * authenticated session. Updated once via onAuthStateChange — zero extra
 * network round-trips per query (fixes the per-query getSession() overhead).
 */
let _hasSupabaseSession = false;

function getRawSupabase() {
  if (!_supabase) {
    _supabase = createSupabaseClient();
    registerRawClientGetter(() => _supabase);

    // Listen to auth state changes to keep the cached flag in sync
    _supabase.auth.onAuthStateChange((_event, session) => {
      _hasSupabaseSession = !!session;
    });

    // Populate the initial value without blocking
    _supabase.auth.getSession().then(({ data }) => {
      _hasSupabaseSession = !!data?.session;
    }).catch(() => {});
  }
  return _supabase;
}

class HybridQueryBuilder {
  private table: string;
  private method: "select" | "insert" | "update" | "delete" | "upsert" = "select";
  private selectFields: string = "*";
  private hasSelect: boolean = false;
  private payload: any = null;
  private filters: Array<{ type: string; field: string; value: any }> = [];
  private orderField: string | null = null;
  private orderAscending: boolean = false;
  private limitCount: number | null = null;
  private isSingle: boolean = false;
  private isMaybeSingle: boolean = false;

  constructor(table: string) {
    this.table = table;
  }

  select(fields?: string) {
    this.hasSelect = true;
    if (fields) this.selectFields = fields;
    return this;
  }

  insert(payload: any) {
    this.method = "insert";
    this.payload = payload;
    return this;
  }

  update(payload: any) {
    this.method = "update";
    this.payload = payload;
    return this;
  }

  delete() {
    this.method = "delete";
    return this;
  }

  eq(field: string, value: any) {
    this.filters.push({ type: "eq", field, value });
    return this;
  }

  neq(field: string, value: any) {
    this.filters.push({ type: "neq", field, value });
    return this;
  }

  is(field: string, value: any) {
    this.filters.push({ type: "is", field, value });
    return this;
  }

  order(field: string, options?: { ascending?: boolean }) {
    this.orderField = field;
    this.orderAscending = options?.ascending ?? false;
    return this;
  }

  limit(n: number) {
    this.limitCount = n;
    return this;
  }

  single() {
    this.isSingle = true;
    return this;
  }

  maybeSingle() {
    this.isMaybeSingle = true;
    return this;
  }

  // Promise/Thenable interface
  async then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    try {
      const result = await this.execute();
      if (onfulfilled) return onfulfilled(result);
      return result;
    } catch (err) {
      if (onrejected) return onrejected(err);
      throw err;
    }
  }

  private async execute() {
    const raw = getRawSupabase();

    // Use the module-level cached session flag — no extra network call per query.
    // A vault-only session (offline admin) falls back to local DB unless there is
    // also a live Supabase session (set by the under-the-hood auto-login in auth.tsx).
    const isVaultSession = typeof window !== "undefined" && !!localStorage.getItem("vault_session_id");
    const isOnline = typeof navigator !== "undefined" && navigator.onLine && (!isVaultSession || _hasSupabaseSession);

    if (isOnline) {
      try {
        let q = raw.from(this.table);
        if (this.method === "select") {
          q = q.select(this.selectFields) as any;
        } else if (this.method === "insert") {
          // Always request returning data to keep local storage in sync
          q = q.insert(this.payload).select(this.selectFields) as any;
        } else if (this.method === "update") {
          q = q.update(this.payload).select(this.selectFields) as any;
        } else if (this.method === "delete") {
          q = q.delete() as any;
        }

        for (const f of this.filters) {
          if (f.type === "eq") q = q.eq(f.field, f.value) as any;
          else if (f.type === "neq") q = q.neq(f.field, f.value) as any;
          else if (f.type === "is") q = q.is(f.field, f.value) as any;
        }

        if (this.orderField) {
          q = q.order(this.orderField, { ascending: this.orderAscending }) as any;
        }
        if (this.limitCount !== null) {
          q = q.limit(this.limitCount) as any;
        }
        if (this.isSingle) {
          q = q.single() as any;
        } else if (this.isMaybeSingle) {
          q = q.maybeSingle() as any;
        }

        const { data, error } = await q;
        if (!error) {
          // Success! Sync online change to offline ldb
          this.syncOnlineToLocal(data);
          
          if (typeof window !== "undefined") {
            window.dispatchEvent(new CustomEvent("database-change"));
          }
          
          // If the caller did NOT explicitly request returned data on insert/update,
          // return data: null to match standard Supabase behavior
          const returnedData = this.hasSelect ? data : null;
          return { data: returnedData, error: null };
        } else {
          // Check if error is network related, if so fallback offline
          const errMsg = error.message || String(error);
          if (errMsg.includes("offline") || errMsg.includes("Failed to fetch") || errMsg.includes("NetworkError") || errMsg.includes("AbortError")) {
            return await this.executeOffline();
          }
          return { data: null, error };
        }
      } catch (err: any) {
        return await this.executeOffline();
      }
    } else {
      return await this.executeOffline();
    }
  }

  private syncOnlineToLocal(data: any) {
    // Skip internal log table caching if not needed, but keep core data
    if (this.table === "activity_log") return;
    
    // If we have actual returned data, upsert it in local ldb
    if (data) {
      if (Array.isArray(data)) {
        const localRows = ldb.getTableData(this.table);
        const map = new Map(localRows.map((r: any) => [r.id, r]));
        for (const row of data) {
          map.set(row.id, { ...map.get(row.id), ...row });
        }
        ldb.setTableData(this.table, Array.from(map.values()));
      } else if (data && typeof data === "object") {
        const localRows = ldb.getTableData(this.table);
        if (localRows.some((r: any) => r.id === data.id)) {
          ldb.update(this.table, data.id, data);
        } else {
          ldb.insert(this.table, data);
        }
      }
    } else {
      // Fallback: apply payload writes directly to local cache
      if (this.method === "insert" && this.payload) {
        const rows = Array.isArray(this.payload) ? this.payload : [this.payload];
        for (const r of rows) {
          const localRows = ldb.getTableData(this.table);
          if (r.id && !localRows.some((lr: any) => lr.id === r.id)) {
            ldb.insert(this.table, r);
          } else if (!r.id) {
            ldb.insert(this.table, r);
          }
        }
      } else if (this.method === "update" && this.payload) {
        let targetId = "";
        for (const f of this.filters) {
          if (f.field === "id" && f.type === "eq") {
            targetId = f.value;
          }
        }
        if (targetId) {
          ldb.update(this.table, targetId, this.payload);
        }
      } else if (this.method === "delete") {
        for (const f of this.filters) {
          if (f.field === "id" && f.type === "eq") {
            ldb.delete(this.table, f.value);
          }
        }
      }
    }
  }

  private async executeOffline() {
    console.info(`[Offline DB] Running ${this.method} on table: ${this.table}`);
    
    // Dispatch local change event for mutating methods (insert, update, delete)
    if (this.method !== "select" && typeof window !== "undefined") {
      setTimeout(() => {
        window.dispatchEvent(new CustomEvent("database-change"));
      }, 0);
    }
    
    if (this.method === "select") {
      let rows = ldb.all(this.table);
      
      // Apply filters
      rows = rows.filter((row: any) => {
        for (const f of this.filters) {
          const val = row[f.field];
          if (f.type === "eq") {
            if (val !== f.value) return false;
          } else if (f.type === "neq") {
            if (val === f.value) return false;
          } else if (f.type === "is") {
            if (f.value === null) {
              if (val !== null && val !== undefined) return false;
            } else {
              if (val !== f.value) return false;
            }
          }
        }
        return true;
      });
      
      // Apply order
      if (this.orderField) {
        const field = this.orderField;
        const asc = this.orderAscending;
        rows.sort((a: any, b: any) => {
          const av = a[field];
          const bv = b[field];
          if (av === bv) return 0;
          if (av === null || av === undefined) return 1;
          if (bv === null || bv === undefined) return -1;
          if (typeof av === "number" && typeof bv === "number") {
            return asc ? av - bv : bv - av;
          }
          const as = String(av);
          const bs = String(bv);
          return asc ? as.localeCompare(bs) : bs.localeCompare(as);
        });
      }
      
      // Apply joins
      rows = rows.map((row: any) => {
        const copy = { ...row };
        if (this.table === "bookings") {
          const slots = ldb.all("time_slots");
          copy.slot = slots.find((s: any) => s.id === copy.slot_id) || null;
        } else if (this.table === "incomes") {
          const types = ldb.all("income_types");
          copy.type = types.find((t: any) => t.id === copy.type_id) || null;
        } else if (this.table === "expenses") {
          const types = ldb.all("expense_types");
          copy.type = types.find((t: any) => t.id === copy.type_id) || null;
        }
        return copy;
      });
      
      // Apply limit
      if (this.limitCount !== null) {
        rows = rows.slice(0, this.limitCount);
      }
      
      if (this.isSingle || this.isMaybeSingle) {
        return { data: rows[0] || null, error: null };
      }
      
      return { data: rows, error: null };
    }
    
    if (this.method === "insert") {
      const row = {
        ...this.payload,
        id: this.payload.id || "offline-" + Math.random().toString(36).substr(2, 9),
      };
      
      if (this.table === "bookings" && !row.order_id) {
        row.order_id = `BK-${Date.now().toString().slice(-6)}`;
      }
      
      const inserted = ldb.insert(this.table, row);
      ldb.addToPendingSyncQueue({
        table: this.table,
        action: "insert",
        payload: inserted,
      });
      
      if (this.isSingle || this.isMaybeSingle) {
        return { data: inserted, error: null };
      }
      const data = this.hasSelect ? [inserted] : null;
      return { data, error: null };
    }
    
    if (this.method === "update") {
      let targetId = "";
      for (const f of this.filters) {
        if (f.field === "id" && f.type === "eq") {
          targetId = f.value;
        }
      }
      
      if (targetId) {
        const updated = ldb.update(this.table, targetId, this.payload);
        ldb.addToPendingSyncQueue({
          table: this.table,
          action: "update",
          targetId,
          payload: this.payload,
        });
        
        if (this.isSingle || this.isMaybeSingle) {
          return { data: updated, error: null };
        }
        const data = this.hasSelect ? [updated] : null;
        return { data, error: null };
      } else {
        // Bulk update
        let rows = ldb.all(this.table);
        const matches = rows.filter((row: any) => {
          for (const f of this.filters) {
            const val = row[f.field];
            if (f.type === "eq") {
              if (val !== f.value) return false;
            } else if (f.type === "neq") {
              if (val === f.value) return false;
            } else if (f.type === "is") {
              if (f.value === null) {
                if (val !== null && val !== undefined) return false;
              } else {
                if (val !== f.value) return false;
              }
            }
          }
          return true;
        });

        const updatedRows = [];
        for (const r of matches) {
          const updated = ldb.update(this.table, r.id, this.payload);
          ldb.addToPendingSyncQueue({
            table: this.table,
            action: "update",
            targetId: r.id,
            payload: this.payload,
          });
          if (updated) updatedRows.push(updated);
        }

        if (this.isSingle || this.isMaybeSingle) {
          return { data: updatedRows[0] || null, error: null };
        }
        const data = this.hasSelect ? updatedRows : null;
        return { data, error: null };
      }
    }
    
    if (this.method === "delete") {
      let rows = ldb.all(this.table);
      
      // Filter rows to be deleted
      const toDelete = rows.filter((row: any) => {
        for (const f of this.filters) {
          const val = row[f.field];
          if (f.type === "eq") {
            if (val !== f.value) return false;
          } else if (f.type === "neq") {
            if (val === f.value) return false;
          } else if (f.type === "is") {
            if (f.value === null) {
              if (val !== null && val !== undefined) return false;
            } else {
              if (val !== f.value) return false;
            }
          }
        }
        return true;
      });

      for (const r of toDelete) {
        ldb.delete(this.table, r.id);
        ldb.addToPendingSyncQueue({
          table: this.table,
          action: "delete",
          targetId: r.id,
        });
      }

      return { data: null, error: null };
    }
    
    return { data: null, error: new Error("Unsupported method offline") };
  }
}

// Proxy wrapper around createSupabaseClient to implement offline database fallbacks
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (prop === "from") {
      return (table: string) => new HybridQueryBuilder(table);
    }
    const raw = getRawSupabase();
    return Reflect.get(raw, prop, receiver);
  },
});
