// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Global fetch with a hard 3-second timeout injected into Supabase.
 * Every request across the entire app now fails fast when the backend
 * is unreachable — no per-call wrappers needed, retries are also bounded.
 */
function timeoutFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 3_000);
  return fetch(input, { ...init, signal: controller.signal })
    .catch((err: Error) => {
      clearTimeout(timer);
      if (err.name === "AbortError") {
        throw new Error("Server is offline. Changes cannot be saved right now.");
      }
      throw err;
    })
    .finally(() => clearTimeout(timer));
}

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || "https://icjeiuuqvysjakhubcgaw.supabase.co";
  const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_KEY) {
    console.error("Missing Supabase API Key in .env");
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_KEY || "", {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: false, // Don't keep retrying auth when offline
    },
    global: {
      fetch: timeoutFetch, // ← The root fix: every request times out in 3s
    },
    realtime: {
      reconnectAfterMs: () => 60_000, // Don't spam reconnect attempts
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
